//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangWei.Web.BackSale {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBackDate;
		protected global::System.Web.UI.WebControls.TextBox txtDept_ID;
		protected global::System.Web.UI.WebControls.TextBox txtStoreHouse_ID;
		protected global::System.Web.UI.WebControls.TextBox txtEmployee_ID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
