//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangWei.Web.user {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtUser_Id;
		protected global::System.Web.UI.WebControls.TextBox txtUser_Pwd;
		protected global::System.Web.UI.WebControls.TextBox txtAgain_Pwd;
		protected global::System.Web.UI.WebControls.TextBox txtBel_Group;
		protected global::System.Web.UI.WebControls.TextBox txtDiv_Type;
		protected global::System.Web.UI.WebControls.TextBox txtUser_Auth;
		protected global::System.Web.UI.WebControls.TextBox txtAuth_Type;
		protected global::System.Web.UI.WebControls.TextBox txtUser_Status;
		protected global::System.Web.UI.WebControls.TextBox txtCreate_User;
		protected global::System.Web.UI.WebControls.TextBox txtCreate_Date;
		protected global::System.Web.UI.WebControls.TextBox txtCreate_Time;
		protected global::System.Web.UI.WebControls.TextBox txtAppr_User;
		protected global::System.Web.UI.WebControls.TextBox txtAppr_Date;
		protected global::System.Web.UI.WebControls.TextBox txtAppr_Time;
		protected global::System.Web.UI.WebControls.TextBox txtPwd_Date;
		protected global::System.Web.UI.WebControls.TextBox txtErr_Count;
		protected global::System.Web.UI.WebControls.TextBox txtUse_eJCIC;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
