//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangWei.Web.user {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUser_Id;
	protected global::System.Web.UI.WebControls.Label lblUser_Pwd;
	protected global::System.Web.UI.WebControls.Label lblAgain_Pwd;
	protected global::System.Web.UI.WebControls.Label lblBel_Group;
	protected global::System.Web.UI.WebControls.Label lblDiv_Type;
	protected global::System.Web.UI.WebControls.Label lblUser_Auth;
	protected global::System.Web.UI.WebControls.Label lblAuth_Type;
	protected global::System.Web.UI.WebControls.Label lblUser_Status;
	protected global::System.Web.UI.WebControls.Label lblCreate_User;
	protected global::System.Web.UI.WebControls.Label lblCreate_Date;
	protected global::System.Web.UI.WebControls.Label lblCreate_Time;
	protected global::System.Web.UI.WebControls.Label lblAppr_User;
	protected global::System.Web.UI.WebControls.Label lblAppr_Date;
	protected global::System.Web.UI.WebControls.Label lblAppr_Time;
	protected global::System.Web.UI.WebControls.Label lblPwd_Date;
	protected global::System.Web.UI.WebControls.Label lblErr_Count;
	protected global::System.Web.UI.WebControls.Label lblUse_eJCIC;


       
    }
}
