//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhangWei.Web.SaleOrder {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSaleOrder_ID;
	protected global::System.Web.UI.WebControls.Label lblWriteDate;
	protected global::System.Web.UI.WebControls.Label lblInsureDate;
	protected global::System.Web.UI.WebControls.Label lblEndDate;
	protected global::System.Web.UI.WebControls.Label lblDept_ID;
	protected global::System.Web.UI.WebControls.Label lblCustomer_ID;
	protected global::System.Web.UI.WebControls.Label lblEmployee_ID;


       
    }
}
